### PR TITLE
Added rake task for default templates regeneration

### PR DESCRIPTION
**Pull request by andie-chernysh**
Added rake task for default templates regeneration in db from filesystem. This thing is very handy during development.

Also added description for rake tasks, otherwise they are not showed after `rake -T`.

Also updated README.

### CODE REVIEW

**Comment by jfeaver** [comment]
We should merge this (after some small changes) but I am surprised to see this kind of a task being needed.  Let me explain:

At the core, effective_email_templates was built to provide email templates that are editable by an admin so that developers don't have to make changes in the filesystem.  The import task is meant to be run each time a new email is created but I never thought an overwrite task would be necessary.  I think this could be really useful however (especially if we need to add different dynamic variables to the email templates over time).  So, let's merge it.

Small changes that I would like to see made:

- Change the name of the `import_default_views` task to `import_templates`
- Change the name of the `regenerate_default_views` to `overwrite_templates!`

Is an exclamation mark in a task name a valid character?  The overwrite task is dangerous because it can cause changes made by the admin to be lost.  I'd like it to be clear that running the task is dangerous.  If it is straightforward to do, please also:

- Add a confirmation prompt:  "By running this task, all email templates that exist in the database will be overwritten by the templates in the filesystem.  Do you still want to run this task? (Y/n):"

**Comment by danajanssen** [comment]
I've never seen a rake task with a ! in it, and because of that I would suggest to avoid using one. I don't know if it's valid or not... I think the 'overwrite_templates' + confirmation does a good enough warning the user about the dangerous task. I agree with everything else!

**Comment by andie-chernysh** [comment]
Yeah, I agree with Nathan's suggestions (except the `!`).

Why I decided it would be handy - I needed to update default templates several times after they had been imported to db. So I had to remove them via console and import once more every time, or edit them via admin screens. With the help of this rake task we can do that in one step instead of loading console, finding and removing default templates and running import task. My rake task is more intended for **development**. I don't think it will ever be run on production.

I could add a restriction for rake task to be run on development environment only, if you want. But I think that is not necessary. Most likely, person who runs this task will be aware of what they are doing.

What do you think, @jfeaver, @danajanssen ?

**Comment by danajanssen** [comment]
I don't think we need to restrict to development only

-- 
Dana Janssen
Principal, AgileStyle
780.619.8868  |  agilestyle.com <http://www.agilestyle.com>  |  #204 8540
109st Edmonton AB T6G 1E6

**Comment by andie-chernysh** [comment]
@jfeaver, I made requested changes to PR. Could you please check them out and let me know if everything is ok before being merged? Or you can merge and publish new version of the gem yourself, as a gem owner and creator. :)

**Comment by jfeaver** [comment]
@andie-chernysh: I apologize that I didn't see your comment from a couple of weeks ago.  Thanks for explaining why you wanted to add this feature.  I think it is a good addition.  Thanks for making the changes.  I'll merge and update the gem version :)

**Pull request merged**
